
function(GetLibForCurrentBuildType LIB_LIST OUTPUT_VAR)
    if(CMAKE_BUILD_TYPE STREQUAL "Debug")
        list(FIND LIB_LIST "debug" LIB_INDEX_MINUS_ONE)
    else()
        list(FIND LIB_LIST "optimized" LIB_INDEX_MINUS_ONE)
    endif()
    if(LIB_INDEX LESS 0)
        set(${OUTPUT_VAR} ${LIB_LIST} PARENT_SCOPE)
    else()
        math(EXPR LIB_INDEX "${LIB_INDEX_MINUS_ONE} + 1")
        list(GET LIB_LIST ${LIB_INDEX} LIB_NAME)
        set(${OUTPUT_VAR} ${LIB_NAME} PARENT_SCOPE)
    endif()
endfunction()


function(InstallRuntimeFiles FILE_LIST DESTINATION RENAME)
    foreach(FILE_NAME ${FILE_LIST})
        get_filename_component(RESOLVED_FILE ${FILE_NAME} REALPATH)
        if(EXISTS ${RESOLVED_FILE})
            if(RENAME)
                get_filename_component(NAME ${FILE_NAME} NAME)
                install(FILES ${RESOLVED_FILE} DESTINATION ${DESTINATION} RENAME ${NAME})
            else()
                install(FILES ${RESOLVED_FILE} DESTINATION ${DESTINATION})
            endif()
        endif()
    endforeach()
endfunction()
