using SharedBase.Archive;

/// <summary>
///   Thrive-specific types that archives can contain. Values may never be removed or reordered!
/// </summary>
public enum ThriveArchiveObjectType : uint
{
    InvalidThrive = ArchiveObjectType.StartOfCustomTypes,

    Vector3,
    Vector4,
    Quaternion,

    Save,
    SaveInformation,
    GameProperties,
    MicrobeStage,
    TutorialState,
    GameWorld,
    WorldGenerationSettings,
    WorldStatsTracker,
    SimpleStatistic,
    DamageStatistic,
    ReproductionStatistic,
    UnlockProgress,
    DayNightCycle,
    ReproductionOrganelleData,
    TimedWorldOperations,
    GlobalGlaciationEvent,
    MeteorImpactEvent,
    UnderwaterVentEruptionEffect,
    Meteor,
    GlucoseReductionEffect,
    CompoundDiffusionEffect,
    HydrogenSulfideConsumptionEffect,
    NitrogenControlEffect,
    IronOxidationEffect,
    MarineSnowDensityEffect,
    PhotosynthesisProductionEffect,
    VolcanismEffect,
    PatchMap,
    MicrobeSpecies,
    MacroscopicSpecies,
    MulticellularSpecies,
    TutorialMicrobeStageWelcome,
    TutorialMicrobeMovement,
    TutorialGlucoseCollecting,
    TutorialMicrobeEngulfedExplanation,
    TutorialMicrobeEngulfmentExplanation,
    TutorialMicrobeEngulfmentStorageFull,
    TutorialMicrobeMovementExplanation,
    TutorialMicrobePressEditorButton,
    TutorialMicrobeReproduction,
    TutorialMulticellularWelcome,
    TutorialSpeciesMemberDiedTutorial,
    TutorialResourcesAfterSplitTutorial,
    TutorialProcessPanelTutorial,
    TutorialPausingTutorial,
    TutorialOrganelleDivisionTutorial,
    TutorialOpenProcessPanelTutorial,
    TutorialMicrobeUnbind,
    TutorialMicrobeStayingAlive,
    TutorialLeaveColonyTutorial,
    TutorialDayNightTutorial,
    TutorialCheckTheHelpMenu,
    TutorialBecomeMulticellularTutorial,
    TutorialAtpBalanceIntroduction,
    TutorialAutoEvoPrediction,
    TutorialBindingAgentsTutorial,
    TutorialCellEditorIntroduction,
    TutorialChemoreceptorPlacementTutorial,
    TutorialCompoundBalancesTutorial,
    TutorialDigestionStatTutorial,
    TutorialEarlyGameGoalTutorial,
    TutorialEditorRedoTutorial,
    TutorialEditorReportWelcome,
    TutorialEditorTutorialEnd,
    TutorialEditorUndoTutorial,
    TutorialFlagellumPlacementTutorial,
    TutorialFoodChainTabTutorial,
    TutorialMadeNoChangesTutorial,
    TutorialMigrationTutorial,
    TutorialModifyOrganelleTutorial,
    TutorialNegativeAtpBalanceTutorial,
    TutorialNucleusTutorial,
    TutorialOpenTolerancesTabTutorial,
    TutorialPatchMap,
    TutorialStaySmallTutorial,
    TutorialTolerancesTabTutorial,
    DifficultyPreset,
    AutoEvoConfiguration,
    CustomDifficulty,
    PredefinedAutoEvoConfiguration,
    OrganelleDefinition,
    Biome,
    SpeciesRecordLite,
    GenerationRecord,
    BehaviourDictionary,
    EndosymbiosisData,
    InProgressEndosymbiosis,
    EnvironmentalTolerances,
    MembraneType,
    OrganelleLayout,

    // Special flag types
    ExtendedOrganelleLayout = OrganelleLayout | ArchiveObjectType.ExtendedTypeFlag,
}
