name: Bug report
description: Report technical issues (bugs)
body:

- type: markdown
  attributes:
    value: |
      **IMPORTANT**
      Please only submit technical bug reports here. This is not a place to make feature requests or suggestions.
      For that please visit our suggestions site: https://suggestions.revolutionarygamesstudio.com/
      Or our community forums for longer discussions: https://community.revolutionarygamesstudio.com/

- type: textarea
  attributes:
    label: Describe the bug
    placeholder: A clear and concise description of what the bug is.
  validations:
    required: true

- type: textarea
  attributes:
    label: To Reproduce
    description: Steps to reproduce the behaviour.
    placeholder: |
      1. Go to '...'
      2. Click on new game / something else '...'
      3. Play and do '...'
      4. See error
  validations:
    required: false

- type: textarea
  attributes:
    label: Expected behaviour
    description: A clear and concise description of what you expected to happen, instead of what actually happened.
  validations:
    required: false

- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem.
  validations:
    required: false

- type: textarea
  attributes:
    label: System information
    description: >
      Please specify the OS version, GPU info for graphics-related issues,
      and your Thrive version. You can find GPU info in the game logs.
    placeholder: |
      - OS: Windows 10
      - Graphics card: OpenGL ES 3.0 Renderer: GeForce GTX 1080 Ti/PCIe/SSE2
      - Thrive: 0.6.0
  validations:
    required: true

- type: textarea
  attributes:
    label: Game Logs
    description: |
      Please use a text hosting service (for example https://pastebin.com/) to submit your logs.
      You can copy the launcher output or the contents of `log.txt`.
      You can find these log files by reading the game log to see their location.
      For example:
      ```
      Mono: Logfile is: /home/hhyyrylainen/.local/share/godot/mono/mono_logs/2020_07_21 23.10.26 (265121).txt
      Game logs are written to: /home/hhyyrylainen/.local/share/Thrive/logs latest log is 'log.txt'
      ```
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional Context
    description: Add any other context about the problem here.
  validations:
    required: false