using System.Collections.Generic;
using Godot;


/// <summary>
///   A page in the Thriveopedia generated by content from the online wiki.
/// </summary>
public abstract class ThriveopediaWikiPage : ThriveopediaPage
{
    [Export]
    public NodePath MainArticlePath = null!;

    public GameWiki.Page PageContent { get; set; } = null!;

    /// <summary>
    ///   Link to this page in the online wiki.
    /// </summary>
    public string Url => PageContent.Url;

    public override string PageName => PageContent.InternalName;
    public override string TranslatedPageName => TranslationServer.Translate(PageContent.Name);

    protected PackedScene pageSectionScene = null!;
    protected VBoxContainer mainArticle = null!;

    public override void _Ready()
    {
        base._Ready();

        mainArticle = GetNode<VBoxContainer>(MainArticlePath);
        pageSectionScene = GD.Load<PackedScene>("res://src/thriveopedia/pages/wiki/WikiPageSection.tscn");

        foreach (var section in PageContent.Sections)
        {
            AddSection(section.SectionHeading, section.SectionBody);
        }
    }

    public static List<ThriveopediaWikiPage> GenerateAllWikiPages()
    {
        var pages = new List<ThriveopediaWikiPage>();

        var wiki = SimulationParameters.Instance.GetWiki();

        var organellesRootScene = GD.Load<PackedScene>("res://src/thriveopedia/pages/wiki/ThriveopediaOrganellesRootPage.tscn");
        var organellesRootPage = (ThriveopediaOrganellesRootPage)organellesRootScene.Instance();
        organellesRootPage.PageContent = wiki.OrganellesRoot;
        pages.Add(organellesRootPage);

        var organellePageScene = GD.Load<PackedScene>("res://src/thriveopedia/pages/wiki/ThriveopediaOrganellePage.tscn");

        foreach (var organellePage in wiki.Organelles)
        {
            var page = (ThriveopediaOrganellePage)organellePageScene.Instance();
            page.PageContent = organellePage;
            page.Organelle = SimulationParameters.Instance.GetOrganelleType(organellePage.InternalName);
            pages.Add(page);
        }

        return pages;
    }

    protected void AddSection(string? heading, string body)
    {
        var section = (WikiPageSection)pageSectionScene.Instance();

        if (heading != null)
            section.HeadingText = heading;

        section.BodyText = body;
        mainArticle.AddChild(section);
    }
}
