function(print_source_files target)
  if(NOT PRINT_SOURCE_FILES)
    return()
  endif()

  get_target_property(target_sources ${target} SOURCES)
  if(target_sources)
    set(cpp_files "")
    foreach(source ${target_sources})
      if(source MATCHES ".*\\.(cpp|cxx|cc)$")
        get_filename_component(filename ${source} NAME)
        list(APPEND cpp_files ${filename})
      endif()
    endforeach()

    list(LENGTH cpp_files total_files)
    if(total_files GREATER 0)
      list(SORT cpp_files)
      message(STATUS "Files for ${target}:")
      foreach(filename ${cpp_files})
        message(STATUS "  ${filename}")
      endforeach()
    endif()
  endif()
endfunction()
